# Generated by Django 6.0 on 2026-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=100)),
                ('paragraph_1', models.TextField()),
                ('paragraph_2', models.TextField(blank=True, null=True)),
                ('years_experience', models.CharField(max_length=10)),
                ('projects_completed', models.CharField(max_length=10)),
                ('happy_clients', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default="Hello, I'm", max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('description', models.TextField()),
                ('cv_link', models.URLField(blank=True, help_text='Link to your resume/CV', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
