# Generated by Django 6.0 on 2026-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_aboutsection_herosection_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Facebook, GitHub, LinkedIn', max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='e.g. fab fa-facebook', max_length=50)),
            ],
        ),
    ]
