# Generated by Django 6.0 on 2026-04-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='fab fa-html5', help_text='FontAwesome class e.g. fab fa-react', max_length=100),
        ),
    ]
